# Generated by Django 5.0.4 on 2024-04-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.TextField(default='')),
                ('video_title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('publish_time', models.DateTimeField(default='')),
                ('thumbnail_url', models.TextField(default='')),
                ('channel_title', models.TextField(default='')),
            ],
            options={
                'indexes': [models.Index(fields=['publish_time'], name='api_youtube_publish_da7346_idx')],
            },
        ),
    ]
